In [2]:
# Load libraries
import numpy as np
from keras import models
from keras import layers
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.datasets import make_classification
import csv
import pandas as pd 
from scikeras.wrappers import KerasClassifier, KerasRegressor

# Set random seed
np.random.seed(0)

In [3]:
#open and read file

#file = open('DATA.csv')

#csvreader = csv.reader(file)
data= pd.read_csv("DATA.csv", delimiter=';')
data

,STUDENT ID,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,COURSE ID,GRADE
0,STUDENT1,2,2,3,3,1,2,2,1,1,...,1,1,3,2,1,2,1,1,1,1
1,STUDENT2,2,2,3,3,1,2,2,1,1,...,1,1,3,2,3,2,2,3,1,1
2,STUDENT3,2,2,2,3,2,2,2,2,4,...,1,1,2,2,1,1,2,2,1,1
3,STUDENT4,1,1,1,3,1,2,1,2,1,...,1,2,3,2,2,1,3,2,1,1
4,STUDENT5,2,2,1,3,2,2,1,3,1,...,2,1,2,2,2,1,2,2,1,1
5,STUDENT6,2,2,2,3,2,2,2,2,1,...,1,1,1,2,1,2,4,4,1,2
6,STUDENT7,1,2,2,4,2,2,2,1,1,...,1,1,3,3,3,3,4,4,1,5
7,STUDENT8,1,1,2,3,1,1,1,2,2,...,3,1,3,2,2,1,1,1,1,2
8,STUDENT9,2,1,3,3,2,1,1,1,1,...,1,1,3,2,2,2,4,3,1,5
9,STUDENT10,2,1,2,3,2,2,1,3,4,...,1,1,2,2,2,2,1,2,1,0
10,STUDENT11,1,1,1,3,2,2,2,3,2,...,1,1,2,2,2,2,1,1,1,2
11,STUDENT12,1,1,1,4,1,1,2,4,2,...,3,2,3,1,3,3,4,3,1,0
12,STUDENT13,1,1,1,4,2,2,2,1,1,...,1,1,2,2,2,3,4,2,1,0
13,STUDENT14,2,1,2,5,2,2,2,1,1,...,1,1,3,2,3,3,4,2,1,1
14,STUDENT15,3,2,2,4,1,1,2,3,4,...,1,1,2,3,2,1,4,4,1,2
15,STUDENT16,2,2,2,3,2,2,2,1,1,...,1,1,3,2,2,3,2,2,1,2
16,STUDENT17,1,1,2,5,2,1,2,1,1,...,1,1,3,2,3,3,4,3,1,1
17,STUDENT18,2,2,2,3,2,2,2,1,1,...,1,1,2,2,2,2,2,2,1,2
18,STUDENT19,1,1,2,4,2,2,2,3,1,...,1,1,3,1,3,3,3,3,1,2
19,STUDENT20,1,2,1,3,2,2,1,2,2,...,1,1,3,2,2,3,2,3,1,3
20,STUDENT21,1,2,2,5,1,2,1,1,4,...,1,2,3,1,2,3,4,4,1,1
21,STUDENT22,1,2,2,5,2,2,1,1,4,...,1,1,3,1,3,3,3,3,1,1
22,STUDENT23,2,2,2,3,1,2,1,1,1,...,1,2,3,1,2,3,3,3,1,3
23,STUDENT24,3,2,2,2,1,1,2,5,1,...,1,1,3,2,3,3,3,3,1,1
24,STUDENT25,2,2,2,3,2,2,2,2,1,...,1,1,2,1,3,2,4,4,1,2
25,STUDENT26,2,2,2,3,2,2,1,1,1,...,1,1,2,1,3,2,1,2,1,3
26,STUDENT27,2,2,2,3,2,1,1,1,1,...,1,1,3,3,3,2,2,1,1,1
27,STUDENT28,1,2,1,3,1,2,2,1,1,...,1,1,3,1,2,1,2,1,1,1
28,STUDENT29,3,2,2,3,2,2,1,1,4,...,1,1,3,2,3,3,5,4,1,3
29,STUDENT30,2,2,3,4,2,2,2,1,4,...,1,1,3,2,2,2,4,3,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,STUDENT116,2,1,2,5,1,2,1,1,1,...,2,2,3,2,3,2,2,2,8,1
116,STUDENT117,2,1,2,5,2,2,2,1,1,...,1,1,3,3,3,1,2,3,8,1
117,STUDENT118,3,1,1,3,2,1,2,1,1,...,1,1,2,3,2,1,2,3,8,1
118,STUDENT119,1,2,2,5,2,1,1,1,4,...,3,1,3,3,2,2,3,3,8,1
119,STUDENT120,2,1,2,4,2,1,2,1,1,...,1,2,2,2,3,1,3,3,8,2
120,STUDENT121,2,1,1,3,1,1,1,2,2,...,2,1,3,3,3,2,2,2,8,1
121,STUDENT122,2,1,2,3,1,1,1,1,2,...,2,1,1,1,1,1,1,1,8,0
122,STUDENT123,1,2,2,5,2,1,2,1,1,...,2,1,3,2,2,1,4,3,8,2
123,STUDENT124,2,1,3,3,2,2,2,3,1,...,1,1,3,3,2,1,1,1,8,1
124,STUDENT125,1,1,2,4,1,1,1,1,1,...,2,2,3,3,2,1,3,3,9,3
125,STUDENT126,1,1,2,5,1,1,2,1,1,...,1,2,3,2,3,1,1,3,9,2
126,STUDENT127,1,1,1,4,1,1,1,3,2,...,2,1,3,3,3,1,2,2,9,3
127,STUDENT128,1,1,2,4,2,2,2,1,4,...,1,1,3,2,2,1,2,2,9,1
128,STUDENT129,1,1,2,4,2,1,1,1,4,...,1,1,3,2,2,1,2,2,9,0
129,STUDENT130,1,1,2,3,1,1,2,1,1,...,2,2,3,2,3,2,2,3,9,3
130,STUDENT131,1,1,2,3,1,1,2,1,1,...,1,2,3,1,3,2,2,3,9,1
131,STUDENT132,1,1,1,5,2,1,2,1,2,...,1,2,3,2,3,1,5,3,9,4
132,STUDENT133,1,1,1,5,2,1,2,1,1,...,2,1,3,2,3,1,5,4,9,3
133,STUDENT134,1,1,2,5,2,2,1,1,1,...,1,1,3,3,3,2,5,3,9,3
134,STUDENT135,1,1,2,4,2,1,2,1,2,...,1,1,2,1,2,1,2,3,9,1
135,STUDENT136,2,1,2,3,1,1,2,1,4,...,1,1,3,3,2,1,3,2,9,2
136,STUDENT137,1,1,2,3,1,1,1,1,2,...,3,1,3,2,2,1,2,2,9,0
137,STUDENT138,1,1,1,5,2,1,2,1,1,...,1,1,3,1,3,1,2,4,9,2
138,STUDENT139,1,1,2,4,1,1,1,5,2,...,2,1,3,2,3,1,1,3,9,0
139,STUDENT140,1,1,2,4,1,2,1,2,2,...,2,1,2,3,2,1,1,2,9,0
140,STUDENT141,2,1,2,3,1,1,2,1,1,...,1,1,2,1,2,1,3,3,9,5
141,STUDENT142,1,1,2,4,2,2,2,1,4,...,1,1,3,2,2,1,5,3,9,5
142,STUDENT143,1,1,1,4,2,2,2,1,1,...,1,1,3,3,2,1,4,3,9,1
143,STUDENT144,2,1,2,4,1,1,1,5,2,...,2,1,2,1,2,1,5,3,9,4
144,STUDENT145,1,1,1,5,2,2,2,3,1,...,2,1,3,2,3,1,5,4,9,3

In [5]:
df = pd.DataFrame(data)

X_columns = df.columns.drop(['STUDENT ID', 'COURSE ID', 'GRADE'])

In [7]:
X = df.drop(['STUDENT ID', 'COURSE ID', 'GRADE'], axis = 1)
y = df['GRADE']

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X)

StandardScaler()

In [9]:
X_columns = df.columns.drop(['STUDENT ID', 'COURSE ID', 'GRADE'])
X = pd.DataFrame(scaler.transform(X), columns=X_columns)

In [11]:
from imblearn.over_sampling import SMOTENC

sample = SMOTENC(categorical_features=[df.dtypes==object], random_state=42)

sampled_X, sampled_y = sample.fit_resample(X, y)

C:\Users\taile\Anaconda3\lib\site-packages\scipy\sparse\lil.py:512: FutureWarning: future versions will not create a writeable array from broadcast_array. Set the writable flag explicitly to avoid this warning.
  if not i.flags.writeable or i.dtype not in (np.int32, np.int64):
C:\Users\taile\Anaconda3\lib\site-packages\scipy\sparse\lil.py:514: FutureWarning: future versions will not create a writeable array from broadcast_array. Set the writable flag explicitly to avoid this warning.
  if not j.flags.writeable or j.dtype not in (np.int32, np.int64):
C:\Users\taile\Anaconda3\lib\site-packages\scipy\sparse\lil.py:518: FutureWarning: future versions will not create a writeable array from broadcast_array. Set the writable flag explicitly to avoid this warning.
  if not x.flags.writeable:

In [12]:
#setup the svm, and train it

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
sampled_X_train, sampled_X_test, sampled_y_train, sampled_y_test = train_test_split(sampled_X, sampled_y, test_size=0.3, random_state=42)

In [13]:
from sklearn.svm import LinearSVC
from sklearn.model_selection import GridSearchCV

parameters = {'C':[0.001, 0.01, 0.1, 1, 2, 3, 4, 5, 10]}
grid_search = GridSearchCV(LinearSVC(dual=False), parameters, cv=10)

grid_search.fit(X_train, y_train)
regular_best_estimator = grid_search.best_estimator_

print('Regular Linear SVC: ' + regular_best_estimator.__str__())

C:\Users\taile\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:680: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=10.
  UserWarning,

Regular Linear SVC: LinearSVC(C=0.01, dual=False)

In [14]:
regular_lin_clf = LinearSVC(C = .01, dual=False, random_state=42)
regular_lin_clf.fit(X_train, y_train)

LinearSVC(C=0.01, dual=False, random_state=42)

In [20]:
lin_clf = LinearSVC(C = 2, dual=False, random_state=42)
lin_clf.fit(sampled_X_train, sampled_y_train)

LinearSVC(C=2, dual=False, random_state=42)

In [21]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

prediction = lin_clf.predict(X_train)
confusion_matrix(y_train, prediction)

accuracy_score(y_train, prediction)

0.7029702970297029

In [22]:
from sklearn.metrics import mean_absolute_error

mean_absolute_error(y_train, prediction)

0.8514851485148515

In [24]:
prediction = lin_clf.predict(X_test)
confusion_matrix(y_test, prediction)

array([[4, 1, 0, 0, 0, 0, 0, 0],
       [0, 5, 1, 0, 2, 0, 0, 2],
       [3, 2, 4, 0, 0, 0, 0, 0],
       [1, 1, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 3, 0, 0],
       [0, 1, 0, 0, 0, 0, 3, 1],
       [0, 0, 0, 0, 0, 0, 0, 3]], dtype=int64)

In [25]:
accuracy_score(y_test, prediction)

0.6590909090909091

In [26]:
mean_absolute_error(y_test, prediction)

0.8863636363636364

In [27]:
cross_val_score(regular_lin_clf, X_test, y_test, cv=10).mean()

C:\Users\taile\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:680: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=10.
  UserWarning,

0.1

In [28]:
accuracy_score(y_test, prediction)

0.6590909090909091